### ISSUE TITLE
Is it possible to run Sentence transformes? 

### ISSUE THREAD

**Issue by fugaprascolinas** [deepinfra/deepctl#4]
This library runs the basis for different vector databases and depends in gpu for speed and stability. I am running it in Ec2 using only cpu, but the results are bad.

**Comment by NikolaBorisov** [comment]
@fugaprascolinas We have support for number of sentance transformers models.
You can quickly try them like this:
```
deepctl infer \
    -m 'sentence-transformers/all-MiniLM-L12-v2'  \
    -i 'inputs=["I like chocolate"]
```

Here is a list of the models we have right now: https://stage.deepinfra.com/models?type=embeddings
If you want any of the models on hugging face we can easily add them https://huggingface.co/models?pipeline_tag=sentence-similarity&sort=downloads

If you want to deploy your own custom model let me know, we are working on support for this, should be out soon.

**Comment by NikolaBorisov** [comment]
@fugaprascolinas let me know if this helper. I would like to close this issue.
